#!/usr/bin/env bash

set -eo pipefail

# some packages required for python imports mysqldb and ldap
apt-get update
apt-get install -y \
  libmysqlclient-dev \
  libldap2-dev libsasl2-dev

# clean up unused apt stuff:
rm -r /var/lib/apt/lists/* 

