version: "2"

services:
  #
  # FieldPrime wsgi/app
  # Depends: wsgi_pylibs
  #
  fp_adm:
    build: fpa
    container_name: fp_server
    environment:
      FP_MYSQL_HOST: fp_mysql
      FP_MYSQL_PORT: 3306
    ports:
      - "80:80"
    links:
      - fp_mysql

  #
  # FieldPrime database
  #
  fp_mysql:
    build: fp_mysql
    container_name: fp_mysqldb
    volumes:
      - fp_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foo

volumes:
  fp_dbdata:
    driver: local
