version: '2'

services:

  #
  # Fieldprime django API
  #
  fp_api:
    build: fieldprime-api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - fp_mysql

  #
  # FieldPrime wsgi/app
  # Depends: wsgi_pylibs
  #
  fp_adm:  
    build: fpa
    container_name: fp_server
    environment:
        FP_MYSQL_HOST: fp_mysql
        FP_MYSQL_PORT: 3306
    ports:
        - "80:80"
    links:
      - fp_mysql

  #
  # FieldPrime database
  #
  fp_mysql:
    build: fp_mysql
    container_name: fp_mysqldb
    volumes:
      - fp_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foo
    ports:
        - "3306:3306"

volumes:
  fp_dbdata:
    driver: local

