version: '2'

services:

  #
  # Fieldprime django API
  #
  fieldprime2_api_server:
    build: fieldprime-api
    image: fieldprime2_api_server:latest
    container_name: fieldprime2_api_server
    command: python manage.py runserver 0.0.0.0:8000
    environment:
        FP_MYSQL_HOST: fieldprime_mysql
        FP_MYSQL_PORT: 3306
        FP_MYSQL_PASS: fieldprimepw
    ports:
      - "8000:8000"
    links:
      - fieldprime_mysql

  #
  # FieldPrime wsgi/app
  # Depends: wsgi_pylibs
  #
  fieldprime_server:  
    build: fpa
    image: fieldprime_server:latest
    container_name: fieldprime_server
    environment:
        FP_MYSQL_HOST: fieldprime_mysql
        FP_MYSQL_PORT: 3306
        FP_MYSQL_PASS: fieldprimepw
    ports:
        - "80:80"
    links:
      - fieldprime_mysql

  #
  # FieldPrime database
  #
  fieldprime_mysql:
    build: fp_mysql
    image: fieldprime_mysql:latest
    container_name: fieldprime_mysql
    volumes:
      - fieldprime_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: fieldprimepw
    ports:
        - "3306:3306"

volumes:
  fieldprime_dbdata:
    driver: local

