# Generated by Django 2.1.7 on 2019-05-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
